import React from "react";
import Head from "next/head";
import * as App from "app";

function ContactUs() {
    return (
        <div>
            <Head>
                <title>Contact-Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <App.ContactUs.Main />
        </div>
    );
}

export default ContactUs;
