import React from "react";
import Head from "next/head";
import * as App from "app";

function Pnation() {
  return (
    <div>
      <Head>
        <title>P-nation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App.Pnation.Main />
    </div>
  );
}

export default Pnation;
