import type { NextPage } from 'next'
import Head from 'next/head'
import * as App from 'app'

const Index = () => {
  return (
    <div>
      <Head>
        <title>Pinoy Preneurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App.PinoyPreners.Templates.Main/>
    </div>
  )
}

export default Index