import React from "react";
import Head from "next/head";
import * as Apps from "app";

function Niknok() {
  return (
    <div>
      <Head>
        <title>NikNok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Apps.NikNok.Main />
    </div>
  );
}

export default Niknok;
