import React from "react";
import Head from "next/head";
import * as App from "app";

function FoodTrip() {
  return (
    <div>
      <Head>
        <title>Food Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App.Foodtrip.Main />
    </div>
  );
}

export default FoodTrip;
