import React from "react";
import Head from "next/head";
import * as Apps from "app";

function ViewTambayan() {

  return (
    <div>
      <Head>
        <title>View Tambayan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Apps.ViewTambayan.ViewTambayan />
    </div>
  )
}

export default ViewTambayan