import React from "react";
import Head from "next/head";
import * as App from "app";

function JobCentre() {
    return (
        <div>
            <Head>
                <title>job-centre</title>
                <meta name="job-centre" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <App.jobCentre.Main />
        </div>
    );
}

export default JobCentre;
