import React from "react";
import Head from "next/head";
import * as Apps from "app";

function Tambayan() {
  return (
    <div>
      <Head>
        <title>Tambayan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Apps.Thambayan.Main />
    </div>
  );
}

export default Tambayan;
