import React from "react";
import Head from "next/head";
import * as App from "app";

function BazaarCity() {
  return (
    <div>
      <Head>
        <title>Bazaar City</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App.BazaarCity.Main />
    </div>
  );
}

export default BazaarCity;
