import React from "react";
import Head from "next/head";
import * as App from "app";

function PinoyViewDetails() {
  return (
    <div>
      <Head>
        <title>New pinoy on the block details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App.ViewArticles.Main />
    </div>
  );
}

export default PinoyViewDetails;
