import React from "react";
import Head from "next/head";
import * as App from "app";

function ViewwhatsupDetails() {
  return (
    <div>
      <Head>
        <title>Whats up canada details </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App.ViewArticles.Main/>
    </div>
  );
}

export default ViewwhatsupDetails;
