import type { NextPage } from 'next'
import Head from 'next/head'
import * as App from 'app'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App.Homepage.Main />
    </div>
  )
}

export default Home
